balancer/balancer-deployments

- .github/workflows/deployment-checks.yml
- ci/prepare-config.ts
Support Polygon ZkEVM network. (Needs keys defined by admin.) #21 also has these changes.
- [N/A] Complex code has been commented, including external interfaces
- [N/A] Tests are included for all code paths
> Add CI support for zkevm network

- addresses/arbitrum.json
- addresses/avalanche.json
- addresses/bsc.json
- addresses/gnosis.json
- addresses/goerli.json
- addresses/mainnet.json
- addresses/optimism.json
- addresses/polygon.json
- addresses/sepolia.json
- addresses/zkevm.json
- src/network.ts
- src/task.ts
Improve address lookup file, going from most general to most specific.
Closes #30.
> Improve addresses report

- README.md
The logo is included in the repo, but the link in the main readme was off.
N/A
> Fix logo link.

- tasks/20230529-avalanche-root-gauge-factory/test/task.fork.ts
Minor patch to simplify the test in #40.
> `AvalancheRootGauge`: Update block # and adjust test

- addresses/.supported-networks.json
Add small JSON descriptor for supported networks.
This is to support documentation automation. Endpoints not included, since there are many options for each chain (both public and permissioned).
Closes #43
> Add supported networks file

- README.md
- src/helpers/expectEvent.ts
Port from https://github.com/balancer/balancer-v3-monorepo/pull/33 + small link fix.
N/A
> Improve `expectEvent.inIndirectReceipt`

- action-ids/mainnet/action-ids.json
Title is self-explanatory; action ID was missing.
Closes #103.
> Add missing optimism root gauge factory action IDs

- action-ids/sepolia/action-ids.json
- action-ids/sepolia/expected-collisions.json
Just some missing action IDs in Sepolia for reference.
N/A
> Add missing Sepolia action IDs.

- package.json
- yarn.lock
We will need this for V3 / fork tests with Solidity after Cancun.
N/A
> Uppdate hardhat version

- v3/tasks/20241205-v3-stable-pool/readme.md
- v3/tasks/20241205-v3-weighted-pool/readme.md
Little consistency thing fixed in the Routers, but still missing in the pools.
- [N/A] Complex code has been commented, including external interfaces
- [N/A] Tests are included for all code paths
> Add dates to pool readme files

- addresses/arbitrum.json
- addresses/avalanche.json
- addresses/base.json
- addresses/bsc.json
- addresses/fraxtal.json
- addresses/gnosis.json
- addresses/mainnet.json
- addresses/mode.json
- addresses/optimism.json
- addresses/polygon.json
- addresses/sepolia.json
- addresses/zkevm.json
- src/network.ts
- src/task.ts
Add `version` field to the JSON that aggregates deployment addresses.
N/A
> Add version to address lookup

- package.json
- v2/scripts/20220325-veBAL-deployment-coordinator/test/task.fork.ts
- v2/scripts/20220415-veBAL-L2-gauge-setup-coordinator/test/task.fork.ts
- v2/scripts/20220418-veBAL-gauge-fix-coordinator/test/task.fork.ts
- v2/scripts/20220421-smart-wallet-checker-coordinator/test/task.fork.ts
- v2/scripts/20220606-tribe-bal-minter-coordinator/test/task.fork.ts
- v2/scripts/20220610-snx-recovery-coordinator/test/task.fork.ts
- v2/scripts/20220721-gauge-adder-migration-coordinator/test/task.fork.ts
- v2/scripts/20230109-gauge-adder-migration-v2-to-v3/test/task.fork.ts
- v2/scripts/20230130-ta-transition-migrator/test/task.fork.ts
- v2/scripts/20230519-gauge-adder-migration-v3-to-v4/test/task.fork.ts
- v3/tasks/20241205-v3-stable-pool/test/task.fork.ts
- v3/tasks/20241205-v3-weighted-pool/test/task.fork.ts
- v3/tasks/20250120-v3-gyro-2clp/test/task.fork.ts
- v3/tasks/20250121-v3-stable-surge/test/task.fork.ts
- v3/tasks/20250124-v3-gyro-eclp/test/task.fork.ts
- Improve pool tests, making it less error prone for pool and factory versions.
- Skip old scripts when running everything.
- Allow running v2 / v3 separately.
N/A
> Improve fork tests

- README.md
- v3/tasks/20250125-v3-mev-tax-hook/artifact/MevTaxHook.json
- v3/tasks/20250125-v3-mev-tax-hook/index.ts
- v3/tasks/20250125-v3-mev-tax-hook/input.ts
- v3/tasks/20250125-v3-mev-tax-hook/readme.md
- v3/tasks/20250125-v3-mev-tax-hook/test/task.fork.ts
build-info: https://github.com/balancer/balancer-v3-monorepo/commit/11ac09bcb60811403475b54285d8acaef917bd2c
N/A
> Deployment preparation: `MevTaxHook`

- hardhat.config.ts
- package.json
- src/verifier.ts
- yarn.lock
Replace hardhat-etherscan to hardhat-verify.
Closes #172
> Replace hardhat-etherscan to hardhat-verify

- v3/tasks/20250221-v3-cow-swap-fee-burner/input.ts
Simplify appdata for COW burner.
Check with https://explorer.cow.fi/appdata?tab=encode and https://api.cow.fi/docs/#/default/put_api_v1_app_data__app_data_hash_.
N/A
> Cow burner: change app data (no json)

- src/task.ts
This PR fixes an issue where bytecode is sometimes calculated incorrectly.
> Fix issue with saving bytecode state for evm

- src/task.ts
If we use artifacts from another task, the verification part ignores it and looks for artifacts in the current task. This PR fixes this problem.
> Fix verify

- src/task.ts
> Fix verify (#219)

- v3/tasks/20250404-v3-stable-surge-pool-factory-v2/test/task.fork.ts
Follow-up on #225 now that the hook is deployed.
N/A
> Adjust fork test for stable surge pool factory

- action-ids/optimism/action-ids.json
Add missing action IDs for OP.
N/A
> Missing OP action IDs for contract registry

- README.md
- v3/tasks/20250507-v3-erc4626-cow-swap-fee-burner/artifact/ERC4626CowSwapFeeBurner.json
- v3/tasks/20250507-v3-erc4626-cow-swap-fee-burner/index.ts
- v3/tasks/20250507-v3-erc4626-cow-swap-fee-burner/input.ts
- v3/tasks/20250507-v3-erc4626-cow-swap-fee-burner/readme.md
- v3/tasks/20250507-v3-erc4626-cow-swap-fee-burner/test/task.fork.ts
Build-info: https://github.com/balancer/balancer-v3-monorepo/commit/f2c6974b4f3b503422ca99061df2af559970f135
N/A
> Deployment preparation: `ERC4626CowSwapFeeBurner`

- .github/workflows/deployment-checks.yml
- .github/workflows/timelock-authorizer-config.yml
Reduce boilerplate code by using matrix strategy.
Should produce the same outcome.
N/A
> Simplify CI ymls
